name: PyMongonnator build and deployment on Pypi

on:
  push:
    branches:
      - dev
      
jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python-version: [3, 3.5, 3.6, 3.7, 3.8]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v1

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Installing packages for testing
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install -U pip pipenv pytest tox-gh-actions
          pipenv sync --dev

      - name: Running tests
        run: |
          source venv/bin/activate
          tox

  build:
    runs-on: ubuntu-latest
    needs: tests

    steps:
      - name: Checkout repo
        uses: actions/checkout@v1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Build package
        run: |
          python3 setup.py sdist bdist_wheel

      - name: Upload version in artifact
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist/

      - name: Check package
        run: |
          pip install -U pip twine
          twine check dist/*

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download package
        uses: actions/download-artifact@v1
        with:
          name: dist

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Deploy into testpypi
        run: |
          pip install twine
          export TWINE_USERNAME=$TESTPYPI_USERNAME
          export TWINE_PASSWORD=$TESTPYPI_PASSWORD
          twine upload --repository-url https://test.pypi.org/legacy/ dist/*
        env:
          TESTPYPI_PASSWORD: ${{ secrets.TESTPYPI_PASSWORD }}
          TESTPYPI_USERNAME: ${{ secrets.TESTPYPI_USERNAME }}
